### ISSUE TITLE
[Spots] - Additional Notes

### ISSUE THREAD

**Issue by philippluxi** [philippluxi/Archaeological_Fieldwork#38]
User should be able to take additional notes to each spot.

**ToDo:**
- Create new Textview in SpotView
- On "Save" also store the entered text form the new textview
- Extend Spotmodel by
  - Notes: String

**Comment by philippluxi** [comment]
To save space, implement it as a PopUp Window, to save space in the spotview.

**Comment by philippluxi** [comment]
- [x] Create Add Notes Button in Layout
- [x] Add OnClickListener to open PopUp
- [x] Add Layout for Pop Up
  - [x] Display Spot Title
  - [x] Multiline Text
  - [x] Cancel and Save Button
- [x]  Handle Clicks and EditText from NotesPopUp
    - Be sure not to immediately update the SpotDatabase when clicking save in the popup - but only store it in the spot variable from the Spotactivity. Only Update SpotDB by click on save in SpotView
####  
- [x] If notes are already stored, set button text to Show/Edit Notes in SpotLayout
